spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sberstart
    username: postgres
    password: od3FQGcT
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  jpa:
    open-in-view: false